version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  target-branch: "master"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
  - juliushaertl
  - jakobroehrl
#- package-ecosystem: npm
#  directory: "/"
#  target-branch: "stable1.1"
#  schedule:
#    interval: weekly
#    day: saturday
#    time: "03:00"
#    timezone: Europe/Paris
#  open-pull-requests-limit: 10
#  reviewers:
#  - juliushaertl
#  - jakobroehrl
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
  - juliushaertl
  ignore:
  - dependency-name: christophwurst/nextcloud
    versions:
    - "< 16"
    - ">= 15.a"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
  - juliushaertl
