root: true


extends:
  - eslint:recommended

env:
  browser: true
  amd: true

globals:
  app: false
  angular: false
  $: false
  escapeHTML: false
  OC: false
  OCA: false
  t: false
  oc_current_user: false
  oc_requesttoken: false
  Clipboard: false
  oc_defaults: false

rules:
  curly: error
  eqeqeq: ["error", "smart"]
  guard-for-in: error
  no-console: off
  no-fallthrough: error
  no-mixed-spaces-and-tabs: error
  no-unused-vars: warn
  no-use-before-define: error
  semi: ["error", "always"]
  indent:
    - error
    - tab
    - SwitchCase: 1
